name: Push closed Nuget PR to Main

on:
  workflow_dispatch:

  pull_request:
      types: [ "closed" ]
      branches: [ "main" ]

jobs:
    ci-cd:
        permissions:
            security-events: write
            contents: write
            packages: write
        uses: TostCorp/.github/jobs/pr-closed-nuget.yml
        secrets:
            AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NUGET_GITHUB_USERNAME: ${{ secrets.NUGET_GITHUB_USERNAME }}
            AUTH_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
