name: Push new Nuget PR

on:
  workflow_dispatch:

  pull_request:
      types: [ "opened", "synchronize", "reopened" ]
      branches: [ "main" ]

jobs:
    ci-cd:
        permissions:
            security-events: write
            contents: write
            packages: write
        uses: TostCorp/.github/workflows/jobs/pr-new-nuget.yml
        secrets:
            AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NUGET_GITHUB_USERNAME: ${{ secrets.NUGET_GITHUB_USERNAME }}
            AUTH_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
